// Quick test script to preview PR comment output for all single-project scenarios.
// Run with: node test-output.mjs <path-to-rsdoctor-data.json>
//
// Example: node test-output.mjs ../dolly/src/io/rsdoctor-data.json

import fs from 'fs';
import path from 'path';

const filePath = process.argv[2];
if (!filePath) {
  console.error('Usage: node test-output.mjs <path-to-rsdoctor-data.json>');
  process.exit(1);
}

// --- Inline the relevant logic from report.ts ---

const excludedExtensions = ['.js.map', '.css.map', '.ts.map', '.LICENSE.txt'];

function formatBytes(bytes) {
  if (bytes === 0) return '0 B';
  const k = 1024;
  const sizes = ['B', 'KB', 'MB', 'GB'];
  const isNegative = bytes < 0;
  const absBytes = Math.abs(bytes);
  const i = Math.floor(Math.log(absBytes) / Math.log(k));
  const value = (absBytes / Math.pow(k, i)).toFixed(1);
  return `${isNegative ? '-' : ''}${value} ${sizes[i]}`;
}

function calculateDiff(current, baseline) {
  if (!baseline || baseline === 0 || isNaN(baseline)) return { value: '-', emoji: '❓' };
  const diff = current - baseline;
  if (diff === 0) return { value: '0', emoji: '' };
  const percent = (diff / baseline) * 100;
  if (diff > 0) return { value: `+${formatBytes(diff)} (+${percent.toFixed(1)}%)`, emoji: '📈' };
  return { value: `${formatBytes(diff)} (${percent.toFixed(1)}%)`, emoji: '📉' };
}

function parseRsdoctorData(filePath) {
  const data = JSON.parse(fs.readFileSync(filePath, 'utf8'));
  const { assets, chunks } = data.data.chunkGraph;

  let totalSize = 0, jsSize = 0, cssSize = 0, htmlSize = 0, otherSize = 0;

  const assetAnalysis = assets.reduce((acc, asset) => {
    if (excludedExtensions.some(ext => asset.path.endsWith(ext))) return acc;
    totalSize += asset.size;
    let type = 'other';
    if (asset.path.endsWith('.js'))        { type = 'js';   jsSize   += asset.size; }
    else if (asset.path.endsWith('.css'))  { type = 'css';  cssSize  += asset.size; }
    else if (asset.path.endsWith('.html')) { type = 'html'; htmlSize += asset.size; }
    else                                   {                otherSize += asset.size; }
    acc.push({ path: asset.path, size: asset.size, type });
    return acc;
  }, []);

  return { totalSize, jsSize, cssSize, htmlSize, otherSize, assets: assetAnalysis };
}

function generateProjectMarkdown(projectName, filePath, current, baseline, baselineCommitHash) {
  let md = `### 📁 ${projectName}\n\n`;
  md += `**Path:** \`${filePath}\`\n\n`;

  if (!baseline) {
    md += '> ⚠️ **No baseline data found** - Unable to perform comparison analysis\n\n';
  } else if (baselineCommitHash) {
    md += `> 📌 **Baseline Commit:** \`${baselineCommitHash}\`\n\n`;
  }

  md += '| Metric | Current | Baseline | Change |\n';
  md += '|--------|---------|----------|--------|\n';
  md += `| 📊 Total Size | ${formatBytes(current.totalSize)} | ${baseline ? formatBytes(baseline.totalSize) : '-'} | ${baseline ? calculateDiff(current.totalSize, baseline.totalSize).value : '-'} |\n`;
  md += `| 📄 JavaScript | ${formatBytes(current.jsSize)} | ${baseline ? formatBytes(baseline.jsSize) : '-'} | ${baseline ? calculateDiff(current.jsSize, baseline.jsSize).value : '-'} |\n`;
  md += `| 🎨 CSS | ${formatBytes(current.cssSize)} | ${baseline ? formatBytes(baseline.cssSize) : '-'} | ${baseline ? calculateDiff(current.cssSize, baseline.cssSize).value : '-'} |\n`;
  md += `| 🌐 HTML | ${formatBytes(current.htmlSize)} | ${baseline ? formatBytes(baseline.htmlSize) : '-'} | ${baseline ? calculateDiff(current.htmlSize, baseline.htmlSize).value : '-'} |\n`;
  md += `| 📁 Other Assets | ${formatBytes(current.otherSize)} | ${baseline ? formatBytes(baseline.otherSize) : '-'} | ${baseline ? calculateDiff(current.otherSize, baseline.otherSize).value : '-'} |\n`;
  return md;
}

function buildComment(projectName, relPath, current, baseline, baselineCommitHash) {
  let body = '## Rsdoctor Bundle Diff Analysis\n\n';
  body += generateProjectMarkdown(projectName, relPath, current, baseline, baselineCommitHash);
  body += '*Generated by [Rsdoctor GitHub Action](https://rsdoctor.rs/guide/start/action)*';
  return body;
}

// --- Run the three scenarios ---

const current = parseRsdoctorData(filePath);

// Baseline with changes: shrink JS by 500 KB
const baselineWithChanges = {
  ...current,
  jsSize: current.jsSize + 512000,
  totalSize: current.totalSize + 512000,
};

// Baseline with no changes: identical
const baselineNoChanges = { ...current };

const separator = '\n' + '─'.repeat(60) + '\n';

console.log(separator);
console.log('SCENARIO 1: No baseline (first run)\n');
console.log(buildComment('io', 'src/io/rsdoctor-data.json', current, null, null));

console.log(separator);
console.log('SCENARIO 2: Baseline exists, JS decreased by 500 KB\n');
console.log(buildComment('io', 'src/io/rsdoctor-data.json', current, baselineWithChanges, 'abc1234'));

console.log(separator);
console.log('SCENARIO 3: Baseline exists, no changes\n');
console.log(buildComment('io', 'src/io/rsdoctor-data.json', current, baselineNoChanges, 'abc1234'));
